language: node_js
nodejs:
  - 8

before_install:
- npm install npm@latest -g

addons:
  chrome: stable

script:
  - npm run ci

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  keep-history: true
  github-token: $GITHUB_TOKEN
  verbose: true
  on:
    tags: true
